services:
  backend:
    build:
      context: .
      dockerfile: dockerfile.backend
    volumes:
      - ./env/local_save:/app/local_save
    ports:
      - 8080:8000
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "tutor"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
    volumes:
      - ./env/db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  nginx:
    image: nginx:latest
    ports:
      - 8888:8888
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./env/local_save:/app/local_save
    links:
      - backend